# Generated by Django 5.2.14 on 2026-07-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='exams', to='exam.tag'),
        ),
    ]
