# Generated by Django 5.2.14 on 2026-07-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
