# Generated by Django 5.2.14 on 2026-08-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_quiz_quizoption'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='enrolled_exams', to='member.account'),
        ),
    ]
