# Generated by Django 5.2.14 on 2026-09-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_exam_participants'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedExamResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('score_percent', models.FloatField(default=0)),
                ('earned_xp', models.FloatField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='member.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exam', 'user'), name='unique_limited_exam_result')],
            },
        ),
    ]
