# Generated by Django 5.2.14 on 2026-09-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_limitedexamresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/options/'),
        ),
    ]
