# Generated by Django 5.2.14 on 2026-10-07 14:02

import exam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_quiz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedexamresults',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=exam.models.get_random_quiz_image_name),
        ),
    ]
