# Generated by Django 5.2.14 on 2026-06-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
