# Generated by Django 5.2.14 on 2026-05-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
