# Generated by Django 5.2.14 on 2026-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
