# Generated by Django 5.2.14 on 2026-05-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_account_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='score',
            new_name='xp',
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
