# Generated by Django 5.2.14 on 2026-05-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_rename_score_account_xp_account_avatar_account_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
