# Generated by Django 5.2.14 on 2026-05-19 09:30

import member.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_account_post_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=member.models.get_random_avatar_name),
        ),
    ]
