# Generated by Django 5.2.14 on 2026-05-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
